package net.dark_roleplay.medieval.holders;

import net.dark_roleplay.medieval.DarkRoleplayMedieval;
import net.minecraft.item.Item;
import net.minecraftforge.registries.ObjectHolder;

@ObjectHolder(DarkRoleplayMedieval.MODID)
public class MedievalItems {

	public static final Item
		BARLEY						= null,
		BARLEY_DOUGH				= null,
		BARLEY_FLOUR				= null,
		BAT_EAR						= null,
		BAT_WING					= null,
		BELL_PEPPER					= null,
		BLUEBERRIES					= null,
		BONE_WAR_HORN				= null,
		BRONZE_COIN					= null,
		BUTTER						= null,
		CARAMELIZED_GREEN_APPLE		= null,
		CARAMELIZED_RED_APPLE		= null,
		CARAMELIZED_YELLOW_APPLE	= null,
		CAULIFLOWER					= null,
		CHARCOAL_POWDER				= null,
		CHICKEN_STEW				= null,
		CLEAN_PAINTBRUSH			= null,
		COD_STEW					= null,
		COPPER_COIN					= null,
		COPPER_ORE_CHUNK			= null,
		CUT_GRASS					= null,
		DIRTY_PAINTBRUSH			= null,
		DRY_CLAY_CHUNK				= null,
		EGGPLANT					= null,
		GARLIC						= null,
		GOLD_COIN					= null,
		GOLDEN_TELESCOPE			= null,
		GREEN_APPLE					= null,
		GREEN_PEAR					= null,
		GRILLED_CATFISH				= null,
		GRILLED_WOLF				= null,
		HARDENED_LEATHER			= null,
		HARDENED_LEATHER_STRIP		= null,
		HAY							= null,
		HONEY_COMB					= null,
		HOPS						= null,
		LEATHER_BOOK_COVER			= null,
		ONION						= null,
		PUMPKIN_STEW				= null,
		RAW_CATFISH					= null,
		RAW_WOLF					= null,
		RED_GRAPES					= null,
		ROPE						= null,
		SALPETER_ORE_CHUNK			= null,
		SILVER_COIN					= null,
		SILVER_ORE_CHUNK			= null,
		SILVER_TELESCOPE			= null,
		SPRUCE_TEA					= null,
		STONE_STREET_STOMPER		= null,
		SULFUR_ORE_CHUNK			= null,
		THICK_LEATHER_BOOK_COVER	= null,
		THIN_LEATHER_BOOK_COVER		= null,
		TIN_ORE_CHUNK				= null,
		TRIGGER_TRAP				= null,
		TURNIP						= null,
		VEGETABLE_STEW				= null,
		WHEAT_DOUGH					= null,
		WHEAT_FLOUR					= null,
		WOLF_FUR					= null,
		WOODEN_CUP					= null,
		WOODEN_KEY					= null,
		WOODEN_LOCK					= null,
		WOODEN_STREET_STOMPER		= null,
		WOODEN_WRENCH				= null,
		YELLOW_APPLE				= null,
		YELLOW_PEAR					= null;
	
	public static final Item
		TORCH_HOLDER				= null,
		OAK_SOLID_CHAIR				= null,
		OAK_PLANK_CHAIR				= null,
		OAK_SOLID_CHAIR_ARMREST		= null;
}
